### PR TITLE
Update lodash dependency

### PR DESCRIPTION
**Pull request by kagd**
I am working on a project that is using the latest lodash. Can we update the dep?

Thanks,
- Grant

### CODE REVIEW

**Comment by autoric** [comment]
Grant, this is basically about convenience since bower dependency conflicts are a pain in the ass. With that in mind, this fix for you might just be introducing the same problem for someone else (for instance: me!). 

I would prefer to make the dependency more forgiving. Technically Scheming could be using any 2.x or 3.x version of lodash, so the best solution  would be to change the dependency string to something like:
`"lodash" : "2.x || 3.x"`

Could you update the pull request and confirm that this will prevent bower resolution conflicts in both cases?  

As always, thanks for the contribution!

**Comment by kagd** [comment]
I tested it out locally with `bower link` and ran into 0 conflicts with either version of lodash.

**Comment by autoric** [comment]
Sweet. :+1: 

I'll merge and publish a patch.

**Comment by autoric** [comment]
Should be up at 2.1.4 now. Holler if you have any issues.

**Pull request merged**
